[tool.poetry]
name = "atom-ai"
version = "0.1.0"
description = ""
authors = ["sabyasachi <njoysubho@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
torch = "^2.0.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
